<a href="https://colab.research.google.com/github/StevenMena/01MIAR_Python_IA/blob/main/01MIAR_Exam02_StevenMena.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Examen Segunda Convocatoria

In [3]:
# Your imports HERE !!!!
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


## 01 - 1pt
- Crear una función que devuelva si un año es bisiesto o no
- Un año es bisiesto si es divisible entre 4, excepto aquellos divisibles entre 100 pero no entre 400

In [14]:
leaps = [year for year in range(0, 2021) if is_leap(year)]  # This calls your function is_leap
assert(len(leaps) == 491)  # This will fail if the number of leap years from year 0 is not 491

In [13]:
# Your solution HERE !!!!
def is_leap(year):
  if year % 4 == 0 and (year % 100 != 0 or year % 400 == 0):
      return True
  else:
      return False


## 02 - 1pt
- Resolución de dos sistemas de ecuaciones
    - $ A : \begin{cases} 8x +  2y = 11 \\ -3y + 10x = 44                         \end{cases}$
    
    - $ B : \begin{cases} -4z + y = 5 \\ 3y + 2z = -2 \\ -x -z + 2y = -1 \end{cases}$
- Verifica por código los resultados

In [17]:
# Your solution HERE !!!!
#Sistema A
a = np.array([ [8,2],[-3,10] ])
b  = np.array([11,44])
x,y = np.linalg.solve(a,b)
print('x=' + str(x) + ', y=' + str(y))


#Sistema B
A = np.array([[0, 1, -4], [0, 3, 2], [-1, 2, -1]])
B = np.array([5, -2, -1])
xb,yb,zb = np.linalg.inv(A).dot(B)

print('x=' + str(xb) + ', y=' + str(yb) + ', z=' + str(zb))

x=0.2558139534883721, y=4.476744186046512
x=2.5, y=0.14285714285714285, z=-1.2142857142857142


## 03 - 1pt
- Dadas dos Series de Pandas, implementar una función 'find_not_common' para encontrar los elementos no comunes a ambas Series

In [35]:
p1 = pd.Series([2, 4, 12, 6, 8, 10])
p2 = pd.Series([8, 10, 12, 10, 14, 2, 16, 10])
expected_not_common = pd.Series([4, 6, 14, 16])

not_common = find_not_common(p1, p2)  # This calls tour function find_not_common
not_common.index = np.arange(0, len(not_common))

assert(not_common.equals(expected_not_common)) # This fails if the result is not as expected

In [29]:
# Your solution HERE !!!!

def find_not_common(sr1,sr2):
  sr11 = pd.Series(np.union1d(sr1, sr2))
  sr22 = pd.Series(np.intersect1d(sr1, sr2))
  return sr11[~sr11.isin(sr22)]


#return pd.Series(list(set(p1) & set(p2)))  
  

## 04 - 1pt
- Crear un array de NumPy de dimensiones 5x3, con números enteros aleatorios en el rango [-10, 10]
- Reemplazar todos los valores impares por 0, y todos los valores pares positivos por 1, y los pares negativos por Nan
- Averiguar cuantos elementos tienen Nan por fila

In [38]:
# Your solution HERE !!!!
rand_matrix_4 = np.random.randint(low=-10,high=10,size=(5,3))
print(rand_matrix_4)

mask_1 = np.where(rand_matrix_4 % 2 ==0, rand_matrix_4, 0)
print(mask_1)

mask_2 = np.where((mask_1 % 2 ==0 & mask_1>0), 1, np.np.nan)
print(mask_2)





#Averiguar cuantos elementos tienen Nan por fila
#df = pd.DataFrame(mask_3)
#print(df.isnull().sum(axis=1))

#last_mask = np.where(np.isnan(mask_3), 0, mask_3)

#print(last_mask)




[[-3 -2  4]
 [-4  4 -4]
 [-8 -2  5]
 [ 2  7 -6]
 [-2 -6 -9]]
[[ 0 -2  4]
 [-4  4 -4]
 [-8 -2  0]
 [ 2  0 -6]
 [-2 -6  0]]


ValueError: ignored

## 05 - 1pt
- Dado un diccionario con una lista de nombres de películas y al año concatenado, crear una función que devuelva un DataFrame con dos columnas:
  - Columna 1, el nombre de la película sin el año
  - Columna 2, el año de la película

In [ ]:
movies = {'Name': ["Matrix - 1999", "Cadena Perpetua - 1994", "Parasitos - 2019", "Vengadores, Endgame - 2019", "Interstellar - 2014", 
                   "Django Desencadenado - 2012", "El Padrino - 1972", "El Caballero Oscuro - 2008", "Erase Una Vez En America - 1984", 
                   "El Senyor de los Anillos, La Comunidad del Anillo - 2001"]}
expected_output = pd.DataFrame({'Name':["Matrix", "Cadena Perpetua", "Parasitos", "Vengadores, Endgame", "Interstellar", "Django Desencadenado", 
                                        "El Padrino", "El Caballero Oscuro", "Erase Una Vez En America", "El Senyor de los Anillos, La Comunidad del Anillo"],
                                'Year':["1999", "1994", "2019", "2019", "2014", "2012", "1972", "2008", "1984", "2001"]})
output = extract_year(movies)   # This will call your function extract_year
assert(expected_output.equals(output))  # This will fail if the result is not as expected

In [ ]:
# Your solution HERE !!!!



## 06 - 3pt
- Se tienen tres datasets, se adjuntan sus datos como diccionarios
  - Students, representa un conjunto de alumnos, con sus nombres, edad y sexo
  - Subjects, un conjunto de asignaturas, con su nombre y el semestre en que se imparten
  - Marks, un conjunto de notas que han obtenido los alumnos en las asignaturas
- Obtener la siguiente información usando Pandas
  - Los nombres del alumno con la peor nota, y en que asignatura ha sido
  - Cuantos alumnos tienen asignaturas aprobadas en el primer semestre
  - La media de edad de los asistentes a la asignatura de Math
  - Formar una palabra con las iniciales de los nombres de los estudiantes ordenados por edad descendente, menores de 50 años
- Representar graficamente
  - Las notas medias de todos los estudiantes por asignatura, agrupando por sexo
  - La densidad bivariable de la edad de los estudiantes frente a sus notas, agrupando por sexo (mostrando los datos de dispersion en la zona central, las curvas de densidad en los ejes)

In [ ]:
students = {'StudentId': [1,2,3,4,5,6], 'Name' : ['Philip','Max','Yamileh','Nathan','Uma','Paula'], 'Age' : [22,31,19,44,39,51], 'Sex' : ['M', 'M', 'F', 'M', 'F', 'F']}
subjects = {'SubjectId': [1,2,3], 'Name': ['Python', 'Math', 'DeepLearning'], 'Semester': [1, 1, 2]}
marks = {'StudentId' : [2,2,1,3,6,4,4,3,2,5], 'SubjectId' : [1,3,1,2,1,2,3,1,2,1], 'Mark': [6,5,8,3,5,1,7,2,4,6]}

In [ ]:
# Your solution HERE !!!!

## 07 - 1pt
- Escribir una función 'prime_number' que cada vez que se invoque devuelva el siguiente número primo,  empezando por el 2, hasta cualquier número infinito. Usando plain Python, sin ninguna librería.  Primo es aquel número natural mayor que 1, que solo es divisible por 1 y por si mismo.

In [ ]:
expected_output = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]
g = prime_number()  # This calls your function prime_number
output = [next(g) for n in range(len(expected_output))]
assert(expected_output == output)  # This will fail if the output is not as expected

In [ ]:
# Your solution HERE !!!!

## 08 - 1pt
- Crear una lista aleatoria de 30 edades entre 0 y 99 años
- Discretizar dichas edades en 6 categorías distribuidas con rangos homogéneos (similar cantidad de valores en cada categoría)
- Mostrar las categorías creadas y cuantos elementos hay en cada una de ellas

In [ ]:
# Your solution HERE !!!!

